# 应用服务 WEB 访问端口


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.score.model.domain


spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.100.100:3306/StudentManagementSystem?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 20011127You!
      driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    active: dev
  session:
    timeout: 36000